BEGIN;

INSERT INTO keyword (title, slug) VALUES
('API', 'api'),
('ArduCam', 'arducam'),
('ArgoCD', 'argocd'),
('Architectuur', 'architectuur'),
('Automatisering', 'automatisering'),
('Azure Automation', 'azure-automation'),
('Brood bakken', 'brood-bakken'),
('Caching', 'caching'),
('Cloudarchitectuur', 'cloudarchitectuur'),
('Containers', 'containers'),
('Dancer2', 'dancer2'),
('Desem', 'desem'),
('Docker', 'docker'),
('EduTeams', 'eduteams'),
('ESP32', 'esp32'),
('ESP8266', 'esp8266'),
('Firmware', 'firmware'),
('Flask', 'flask'),
('GitOps', 'gitops'),
('Google OAuth', 'google-oauth'),
('Governance', 'governance'),
('Hardware', 'hardware'),
('HelloID', 'helloid'),
('Identity', 'identity'),
('JSON-LD', 'json-ld'),
('k3s', 'k3s'),
('Kubernetes', 'kubernetes'),
('Markdown', 'markdown'),
('Memcached', 'memcached'),
('Metrics', 'metrics'),
('Microcontrollers', 'microcontrollers'),
('MicroK8s', 'microk8s'),
('Microsoft Graph', 'microsoft-graph'),
('Microsoft Teams', 'microsoft-teams'),
('Monitoring', 'monitoring'),
('OAuth2', 'oauth2'),
('Observability', 'observability'),
('Open Source', 'open-source'),
('Performance', 'performance'),
('Perl', 'perl'),
('Prometheus', 'prometheus'),
('Python', 'python'),
('Scope Creep', 'scope-creep'),
('SEO', 'seo'),
('Softwareontwikkeling', 'softwareontwikkeling'),
('SPI', 'spi'),
('SQLite', 'sqlite'),
('Structured Data', 'structured-data'),
('Template Toolkit', 'template-toolkit'),
('Time-lapse', 'time-lapse'),
('Troubleshooting', 'troubleshooting'),
('UX', 'ux'),
('Zuurdesem', 'zuurdesem');

COMMIT;
