# Session manager
session: "Memcached"

# Externe base URL voor sitemap en andere absolute links
base_url: "https://mysite.prjv.nl/"

# configuration file for production environment

# only log warning and error messages
log: "debug"
loki: 1
# use Log4perl for structured logging
#logger: "Console::Colored"
logger: "log4perl"

log4perl:
  config: |
    log4perl.rootLogger = DEBUG, STDERR
    log4perl.appender.STDERR = Log::Log4perl::Appender::Screen
    log4perl.appender.STDERR.stderr = 1
    log4perl.appender.STDERR.layout = Log::Log4perl::Layout::JSON
    log4perl.appender.STDERR.layout.field.message = %m{chomp}
    log4perl.appender.STDERR.layout.field.level = %p
    log4perl.appender.STDERR.layout.field.logger = %c
    log4perl.appender.STDERR.layout.field.file = %F{1}
    log4perl.appender.STDERR.layout.field.sub = %M{1}
    log4perl.appender.STDERR.layout.field.ts = %d



    # log4perl.appender.STDERR.layout.field.message = %m{chomp}
    # log4perl.appender.STDERR.layout.field.level   = %p
    # log4perl.appender.STDERR.layout.field.logger  = %c
    # log4perl.appender.STDERR.layout.field.file    = %F{1}
    # log4perl.appender.STDERR.layout.field.sub     = %M{1}
    # log4perl.appender.STDERR.layout.utf8 = 1


# hide errors
show_stacktrace: 0

# disable server tokens in production environments
no_server_tokens: 1

plugins:
  DBIC:
    default:
      dsn: "dbi:SQLite:dbname=/app/db/mysite.sqlite"

engines:
  session:
    Memcached:
      memcached_servers: memcached-service:11211

# client_id en client_secret komen uit:
# in dev: .env die in MySite geladen wordt
# in prod: via de Kubernetes secrets
oauth_providers:
  google:
    redirect_uri: "https://mysite.prjv.nl/auth/callback/google"
  github:
    redirect_uri: "https://mysite.prjv.nl/auth/callback/github"
