/* WARNING: Script requires that SQLITE_DBCONFIG_DEFENSIVE be disabled */
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DELETE FROM page_content;
DELETE FROM page;
INSERT INTO page VALUES(1,'About','about',1,'2026-02-12 14:45:12','About page');
INSERT INTO page VALUES(2,'Privacy','privacy',1,'2026-02-12 14:45:12','Privacy page');
INSERT INTO page VALUES(3,'Login','login',1,'2026-02-12 14:45:12','Login page');
INSERT INTO page VALUES(4,'License','license',1,'2026-02-12 14:45:12','MIT License for MySite');
INSERT INTO page_content VALUES(1,1,1,'2026-02-12 14:45:12','2026-02-12 14:45:12',1,replace('\n# About\nNiet veel hier\n	','\n',char(10)));
INSERT INTO page_content VALUES(2,2,1,'2026-02-12 14:45:12','2026-02-12 14:45:12',2,replace('\n# Privacyverklaring\n\nDeze site respecteert jouw privacy. Hieronder lees je wat er gebeurt met jouw gegevens:\n\n- **Login en gebruikersgegevens:**  \n  Je kunt inloggen via Google of GitHub. Bij het inloggen wordt alleen je gebruikersnaam, e-mailadres en (indien beschikbaar) avatar opgeslagen. Er worden geen extra gegevens verzameld of gedeeld met derden.\n\n- **Cookies:**  \n  Er worden alleen functionele cookies gebruikt om je sessie te bewaren tijdens het gebruik van de site. Er worden geen tracking- of advertentiecookies geplaatst.\n\n- **Data-opslag:**  \n  Je gegevens worden opgeslagen in een beveiligde database. Alleen de beheerder heeft toegang tot deze gegevens.\n\n- **Analytics:**  \n  Er wordt geen externe analytics of tracking gebruikt.\n\n- **Contact:**  \n  Voor vragen of verzoeken tot inzage/verwijdering van je gegevens kun je contact opnemen via [prjv.kaagman@gmail.com](mailto:prjv.kaagman@gmail.com).\n\n- **Wijzigingen:**  \n  Deze privacyverklaring kan worden aangepast. De actuele versie is altijd beschikbaar op deze pagina.\n	','\n',char(10)));
INSERT INTO page_content VALUES(3,3,1,'2026-02-12 14:45:12','2026-02-12 14:45:12',1,replace('\n<p>Gebruik één van de volgende diensten om in te loggen. De userid van de gekozen service wordt gebruikt om hier in te loggen of een account voor je te maken.</p>\n<ul>\n    <li><a href="/auth/google">Google</a></li>\n    <li><a href="/auth/github">GitHub</a></li>\n</ul>\n<p><emp>Let op:</emp><br>Diensten als Google en GitHub geven een verschillende userid terug. Gebruik dus altijd dezelfde dienst.</p>\n	','\n',char(10)));
INSERT INTO page_content VALUES(4,4,1,'2026-02-12 14:45:12','2026-02-12 14:45:12',1,replace('\n# MIT License\n\nCopyright (c) 2026 Peter Kaagman\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n','\n',char(10)));
INSERT INTO page_content VALUES(5,2,4,'2026-02-12 14:45:12','2026-02-12 14:45:12',1,replace('\n','\n',char(10)));
COMMIT;
